pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        gradlePluginPortal()
    }
}

buildscript {
    repositories {
        mavenCentral()
    }
    configurations.classpath.resolutionStrategy {
        force 'com.google.code.gson:gson:2.11.0'
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.7.0'
}