modLoader="javafml"
loaderVersion="[46,)"
license="MIT"

[[mods]]
modId="loginsystem"
version="1.3"
displayName="Login System"
description="A login system mod for the Minecraft 1.20 series that enables players to register and login on the server."
minecraft_version_range="[1.20,1.20.7)"
