restrict.command=يجب عليك تسجيل الدخول أولا لاستخدام الأوامر!
restrict.break=لا يمكنك كسر المكعبات قبل تسجيل الدخول!
restrict.drop=لا يمكنك رمي العناصر قبل تسجيل الدخول!
restrict.chat=لا يمكنك التحدث في الشات قبل تسجيل الدخول!
restrict.move=يجب عليك تسجيل الدخول للتحرك!
timeout.bossbar=الوقت المتبقي لتسجيل الدخول
timeout.kick=لقد استغرقت وقتا طويلا لتسجيل الدخول!
register.already=أنت مسجل بالفعل! استخدم /login <password>
register.success=تم التسجيل بنجاح!
register.title=تم التسجيل!
register.subtitle=أهلا بك في السيرفر!
login.already=أنت مسجل الدخول بالفعل!
login.notRegistered=أنت غير مسجل! استخدم /register <password> <password>
login.incorrect=كلمة المرور خاطئة!
login.success=تم تسجيل الدخول بنجاح!
login.title=تم الدخول!
login.subtitle=أهلا بعودتك!
password.mustLogin=يجب عليك تسجيل الدخول أولا!
login.prompt=الرجاء الرجاء تسجيل الدخول بـ /login للعب!
login.promptSubtitle=استخدم /login أو /register
Error.NeedLogin=يجب عليك تسجيل الدخول للتفاعل!
password.changed=تم تغيير كلمة المرور بنجاح!
register.specialChar=يجب أن تحتوي كلمة السر على رمز خاص واحد على الأقل (!@#$%^&*)

