restrict.command=Du musst dich zuerst einloggen, um Befehle zu nutzen!
restrict.break=Du kannst keine Blöcke abbauen, bevor du dich einloggst!
restrict.drop=Du kannst keine Gegenstände fallen lassen, bevor du dich einloggst!
restrict.chat=Du kannst nicht chatten, bevor du dich einloggst!
restrict.move=Du musst dich zuerst einloggen, um dich zu bewegen!
timeout.bossbar=Verbleibende Zeit zum Einloggen
timeout.kick=Du hast zu lange gebraucht, um dich einzuloggen!
register.already=Du bist bereits registriert! Benutze /login <passwort>
register.success=Erfolgreich registriert!
register.title=Registriert!
register.subtitle=Willkommen auf dem Server!
login.already=Du bist bereits eingeloggt!
login.notRegistered=Du bist nicht registriert! Benutze /register <passwort> <passwort>
login.incorrect=Falsches Passwort!
login.success=Erfolgreich eingeloggt!
login.title=Eingeloggt!
login.subtitle=Willkommen zurück!
password.mustLogin=Du musst dich zuerst einloggen!
login.prompt=Bitte logge dich ein oder registriere dich!
login.promptSubtitle=Benutze /login oder /register
Error.NeedLogin=Du musst dich einloggen, um zu interagieren!
password.changed=Passwort erfolgreich geandert!
